config/routes.rb
  match '/help/requesting' => 'help#requesting',
        :as => :help_requesting,
        :via => :get
  match '/help/privacy' => 'help#privacy',
        :as => :help_privacy,
        :via => :get
  match '/help/api' => 'help#api',
        :as => :help_api,
        :via => :get
  match '/help/credits' => 'help#credits',
        :as => :help_credits,
        :via => :get
  match '/help/:template' => 'help#action',
        :as => :help_general,
        :via => :get,
        :template => /[-_a-z]+/
  match '/help' => 'help#index',
        :via => :get
  ####

  #### Holiday controller
  match '/due_date/:holiday' => 'holiday#due_date',
        :as => :due_date,
        :via => :get
  ####

  #### RequestGame controller
  match '/categorise/play' => 'request_game#play',
        :as => :categorise_play,
        :via => [:get, :post]
  match '/categorise/request/:url_title' => 'request_game#show',
        :as => :categorise_request,
        :via => :get
  match '/categorise/stop' => 'request_game#stop',
        :as => :categorise_stop,
        :via => :post
  ####

  #### Announcement controller
  resources :announcements, :only => [:destroy]
  ####

  #### AdminPublicBody controller
  scope '/admin', :as => 'admin' do
    constraints admin_constraint do
      mount Flipper::UI.app(AlaveteliFeatures.backend) => '/flipper'
    end

    resources :bodies,
    :controller => 'admin_public_body' do
      get 'missing_scheme', :on => :collection
      post 'mass_tag_add', :on => :collection
      get 'import_csv', :on => :collection
      post 'import_csv', :on => :collection
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
    end
  end
  ####

  #### AdminPublicBodyCategory controller
  scope '/admin', :as => 'admin' do
    resources :categories,
      :controller => 'admin_public_body_categories'
  end
  ####

  #### AdminPublicBodyHeading controller
  scope '/admin', :as => 'admin'  do
    resources :headings,
      :controller => 'admin_public_body_headings',
    :except => [:index] do
      post 'reorder', :on => :collection
      post 'reorder_categories', :on => :member
    end
  end
  ####

  #### AdminHoliday controller
  scope '/admin', :as => 'admin' do
    resources :holidays,
      :controller => 'admin_holidays'
  end
  ####

  #### AdminHolidayImports controller
  scope '/admin', :as => 'admin' do
    resources :holiday_imports,
      :controller => 'admin_holiday_imports',
      :only => [:new, :create]
  end
  ####

  #### AdminPublicBodyChangeRequest controller
  scope '/admin', :as => 'admin'  do
    resources :change_requests,
      :controller => 'admin_public_body_change_requests',
      :only => [:edit, :update]
  end
  ####

  #### AdminGeneral controller
  match '/admin' => 'admin_general#index',
        :as => :admin_general_index,
        :via => :get
  match '/admin/timeline' => 'admin_general#timeline',
        :as => :admin_timeline,
        :via => :get
  match '/admin/debug' => 'admin_general#debug',
        :as => :admin_debug,
        :via => :get
  match '/admin/stats' => 'admin_general#stats',
        :as => :admin_stats,
        :via => :get
  ####

  #### AdminRequest controller
  scope '/admin', :as => 'admin' do
    resources :requests,
      :controller => 'admin_request',
    :except => [:new, :create] do
      post 'move', :on => :member
      post 'generate_upload_url', :on => :member
      post 'hide', :on => :member
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
    end
  end
  ####

  #### AdminComment controller
  scope '/admin', :as => 'admin' do
    resources :comments,
      :controller => 'admin_comment',
      :only => [:index, :edit, :update]
  end
  ####

  #### AdminRawEmail controller
  scope '/admin', :as => 'admin' do
    resources :raw_emails,
      :controller => 'admin_raw_email',
      :only => [:show]
  end
  ####

  #### AdminInfoRequestEvent controller
  scope '/admin', :as => 'admin' do
    resources :info_request_events,
      :controller => 'admin_info_request_event',
      :only => [:update]
  end

  #### AdminIncomingMessage controller
  scope '/admin', :as => 'admin' do
    resources :incoming_messages,
      :controller => 'admin_incoming_message',
    :only => [:edit, :update, :destroy] do
      post 'redeliver', :on => :member
    end
    resource :incoming_messages,
      :controller => 'admin_incoming_message',
      :only => [:bulk_destroy] do
        post 'bulk_destroy'
      end
  end
  ####

  #### AdminOutgoingMessage controller
  scope '/admin', :as => 'admin' do
    resources :outgoing_messages,
      :controller => 'admin_outgoing_message',
    :only => [:edit, :update, :destroy] do
      post 'resend', :on => :member
    end
  end
  ####

  #### AdminUser controller
  scope '/admin', :as => 'admin' do
    resources :users,
      :controller => 'admin_user',
    :except => [:new, :create, :destroy] do
      get 'banned', :on => :collection
      get 'show_bounce_message', :on => :member
      post 'clear_bounce', :on => :member
      post 'clear_profile_photo', :on => :member
      post 'modify_comment_visibility', :on => :collection
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
      end
  end
  ####

  #### AdminUsersAccountSuspensions controller
  scope '/admin', :as => 'admin' do
    resources :users_account_suspensions,
      :controller => 'admin_users_account_suspensions',
      :only => [:create]
  end
  ####

  #### AdminUsersSessions controller
  scope '/admin', :as => 'admin' do
    resources :users_sessions,
      :controller => 'admin_users_sessions',
      :only => [:create]
  end
  ####

  #### AdminTrack controller
  scope '/admin', :as => 'admin' do
    resources :tracks,
      :controller => 'admin_track',
      :only => [:index, :destroy]
  end
  ####

  #### AdminCensorRule controller
  scope '/admin', :as => 'admin' do
    resources :censor_rules,
      :controller => 'admin_censor_rule'
  end

  #### AdminSpamAddresses controller
  scope '/admin', :as => 'admin' do
    resources :spam_addresses,
      :controller => 'admin_spam_addresses',
      :only => [:index, :create, :destroy]
  end
  ####

  #### AdminAnnouncement controller
  scope '/admin', :as => 'admin' do
    resources :announcements, :controller => 'admin_announcements'
  end
  ####

  #### Api controller
  match '/api/v2/request.json' => 'api#create_request',
        :as => :api_create_request,
        :via => :post

  match '/api/v2/request/:id.json' => 'api#show_request',
        :as => :api_show_request,
        :via => :get
  match '/api/v2/request/:id.json' => 'api#add_correspondence',
        :as => :api_add_correspondence,
        :via => :post
  match '/api/v2/request/:id/update.json' => 'api#update_state',
        :as => :api_update_state,
        :via => :post

  match '/api/v2/body/:id/request_events.:feed_type' => 'api#body_request_events',
        :as => :api_body_request_events,
        :feed_type => '^(json|atom)$',
        :via => :get
  ####

  #### Pro Pricing
  constraints FeatureConstraint.new(:pro_pricing) do

    namespace :alaveteli_pro, path: :pro, as: :pro do
      resources :plans, only: [:index], path: :pricing
      resources :pages, only: [:show]
    end

    scope module: :alaveteli_pro do
      resources :plans, only: [:show]

      scope path: :profile do
        resources :subscriptions, only: [:index, :create, :destroy] do
          collection do
            resource :payment_method, only: [:update]
          end
        end
      end

      match '/pro/subscriptions/stripe-webhook' => 'stripe_webhooks#receive',
            :via => :post
    end

  end

  #### Alaveteli Pro
  constraints FeatureConstraint.new(:alaveteli_pro) do

    scope module: :alaveteli_pro do
      resources :account_request, :only => [:index, :create], path: :pro do
        collection do
          get :training, action: :new
        end
      end
    end

    namespace :alaveteli_pro do
      root to: 'dashboard#index', :as => :dashboard, :via => :get
      resources :draft_info_requests, :only => [:create, :update]
      resources :info_requests, :only => [:new, :create, :update, :index] do
        get :preview, on: :new # /info_request/new/preview
      end
      resources :embargoes, :only => [:destroy, :create] do
        collection do
          post :destroy_batch
        end
      end
      resources :embargo_extensions, :only => [:create] do
        collection do
          post :create_batch
        end
      end
      resources :batch_request_authority_searches, :only => [:index, :new]
      resources :draft_info_request_batches, :only => [:create, :update] do
        collection do
          put :update_bodies
        end
      end
      resources :info_request_batches, :only => [:new, :create] do
        get :preview, on: :new # /info_request_batch/new/preview
      end
      resources :public_bodies, :only => [:index]
    end

    scope path: :alaveteli_pro do
      # So that we can show a request using the existing controller from the
      # pro context
      match '/info_requests/:url_title' => 'request#show',
            :as => :show_alaveteli_pro_request,
            :via => :get,
            :defaults => { :pro => '1' }

      # So that we can show a batch request using the existing controller from
      # the pro context
      match '/info_request_batches/:id' => 'info_request_batch#show',
            :as => :show_alaveteli_pro_batch_request,
            :via => :get,
            :defaults => { :pro => '1' }

      # So that we can show the authority selection screen using the existing
      # controller but in a pro context
      match '/select_authority' => 'request#select_authority',
            :as => :alaveteli_pro_select_authority,
            :via => :get,
            :defaults => { :pro => '1' }
    end

  end
  ####

app/models/alaveteli_pro/account_request.rb
# -*- encoding : utf-8 -*-
# Validates pro account request submissions.
#
# Copyright (c) 2017 UK Citizens Online Democracy. All rights reserved.
# Email: hello@mysociety.org; WWW: http://www.mysociety.org/

class AlaveteliPro::AccountRequest
  include ActiveModel::Validations

  attr_accessor :email,
                :subject,
                :reason,
                :marketing_emails,
                :training_emails,
                :offer_code

  validates_presence_of :email, :message => N_("Please enter your email address")
  validates_presence_of :reason, :message => N_("Please enter the reason why you want access")
  validates_presence_of :marketing_emails, :message => N_("Please tell us if you want to get updates")
  validates_presence_of :training_emails, :message => N_("Please tell us if you're interested in training and seminars")

  validate :email_format

  def initialize(attributes = {})
    return unless attributes
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  private

  def email_format
    unless MySociety::Validate.is_valid_email(email)
      errors.add(:email, _("Email doesn't look like a valid address"))
    end
  end
end

app/models/alaveteli_pro/activity_list/comment.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class Comment < Item

      def description
        if event.comment.user == event.info_request.user
          N_('You added a new annotation on your request to ' \
             '{{public_body_name}} "{{info_request_title}}."')
        else
          N_('{{commenter_name}} added a new annotation on your request to ' \
             '{{public_body_name}} "{{info_request_title}}."')
        end
      end

      def description_urls
        { :public_body_name => { :text => body_name, :url => body_path },
          :info_request_title => { :text => info_request_title, :url => info_request_path },
          :commenter_name => { :text => event.comment.user.name, :url => user_path(event.comment.user) } }
      end

      def call_to_action_url
        comment_path(event.comment)
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/embargo_expiry.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class EmbargoExpiry < Item

      def description
        N_("Your request to {{public_body_name}} \"{{info_request_title}}\" " \
           "is now public.")
      end

      def call_to_action_url
        info_request_path
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/followup_resent.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class FollowupResent < Item

      def description
        case event.calculated_state
        when 'internal_review'
          N_('Your internal review request to {{public_body_name}} for "{{info_request_title}}" was resent.')
        when 'waiting_response'
          N_('Your clarification to {{public_body_name}} for "{{info_request_title}}" was resent.')
        else
          N_('Your follow up to {{public_body_name}} on "{{info_request_title}}" was resent.')
        end
      end

      def call_to_action_url
        outgoing_message_path(event.outgoing_message)
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/followup_sent.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class FollowupSent < Item

      def description
        case event.calculated_state
        when 'internal_review'
          N_('You sent an internal review request to {{public_body_name}} for "{{info_request_title}}".')
        when 'waiting_response'
          N_('You sent a clarification to {{public_body_name}} for "{{info_request_title}}".')
        else
          N_('You sent a follow up to {{public_body_name}} on "{{info_request_title}}".')
        end
      end

      def call_to_action_url
        outgoing_message_path(event.outgoing_message)
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/item.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class Item

      include Rails.application.routes.url_helpers
      include LinkToHelper
      include ActionView::Helpers::DateHelper

      attr_accessor :event

      def initialize(event)
        @event = event
      end

      def info_request_path
        request_path(event.info_request)
      end

      def info_request_title
        event.info_request.title
      end

      def body_name
        event.info_request.public_body.name
      end

      def body_path
        public_body_path(event.info_request.public_body)
      end

      def call_to_action
        _("View")
      end

      def description_urls
        { :public_body_name => { :text => body_name, :url => body_path },
          :info_request_title => { :text => info_request_title, :url => info_request_path } }
      end

      def event_time
        event.created_at
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/list.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList

    class List
      attr_accessor :user, :page, :per_page

      def initialize(user, page, per_page)
        @user = user
        @page = page
        @per_page = per_page
      end

      def event_types
        activity_types.keys
      end

      def events
        user.info_request_events.where(:event_type => event_types)
      end

      def current_items
        current_events = events.paginate :page => page,
                                         :per_page => per_page
        current_events.map{ |event| activity_types[event.event_type].new(event) }
      end

      private

      def activity_types
        {
          "sent" => ActivityList::RequestSent,
          "resent" => ActivityList::RequestResent,
          "followup_sent" => ActivityList::FollowupSent,
          "followup_resent" => ActivityList::FollowupResent,
          "response" => ActivityList::NewResponse,
          "comment" => ActivityList::Comment,
          "overdue" => ActivityList::Overdue,
          "very_overdue" => ActivityList::VeryOverdue,
          "embargo_expiry" => ActivityList::EmbargoExpiry
        }
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/new_response.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class NewResponse < Item

      def description
        N_('Your request to {{public_body_name}} "{{info_request_title}}" received a new response.')
      end

      def call_to_action_url
        incoming_message_path(event.incoming_message)
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/overdue.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class Overdue < Item

      def description
        N_('{{public_body_name}} are delayed in responding to your request "{{info_request_title}}".')
      end

      def call_to_action
        _("Send a follow up")
      end

      def call_to_action_url
        new_request_followup_path(:request_id => event.info_request.id, :anchor => 'followup')
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/request_resent.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class RequestResent < Item

      def description
        N_('Your request "{{info_request_title}}" to {{public_body_name}} was resent.')
      end

      def call_to_action_url
        info_request_path
      end

    end
  end
end

app/models/alaveteli_pro/activity_list/request_sent.rb
# -*- encoding : utf-8 -*-
module AlaveteliPro
  module ActivityList
    class RequestSent < Item

      def description
        N_('You sent a request "{{info_request_title}}" to {{public_body_name}}.')
      end

      def call_to_action_url
        info_request_path
      end

    end
  end
end

app/views/alaveteli_pro/dashboard/_activity_list_item.html.erb
<div class="dashboard-activity__item">
  <div class="dashboard-activity__item__time">
    <% if activity_list_item.event_time >= Time.zone.now - 1.day %>
      <%= _('{{length_of_time}} ago', :length_of_time => time_ago_in_words(activity_list_item.event_time)) %>
    <% else %>
      <%= I18n.l(activity_list_item.event_time, format: '%d %B %Y') %>
    <% end %>
  </div>
  <div class="dashboard-activity__item__description">
    <p>
      <%= activity_item_description(activity_list_item) %>
      <%= link_to activity_list_item.call_to_action,
                  activity_list_item.call_to_action_url %>
    </p>
  </div>
</div>

app/views/alaveteli_pro/dashboard/_announcements.html.erb
<div class="dashboard__announcements carousel" aria-live="polite">
  <ul class="dashboard__announcements__list carousel-content">
    <% @announcements.each_with_index do |announcement, idx| %>
      <li class="dashboard__announcements__list-item carousel-item" aria-hidden="<% if idx.zero? %>false<% else %>true<% end %>">
        <div class="dashboard__announcement">
          <% if announcement.title.present? %><h2 class="dashboard__announcement__title"><%= announcement.title %></h2><% end %>
          <div class="dashboard__announcement__content">
            <p><%= sanitize announcement.content %></p>
          </div>
          <%= link_to _('Dismiss'), announcement_path(announcement), method: :delete, remote: true, class: 'dashboard__announcement_dismiss carousel-item-dismiss' %>
        </div>
      </li>
    <% end %>
  </ul>
  <fieldset aria-label="carousel buttons" class="dashboard__announcements__controls carousel-buttons" aria-controls="carousel">
    <button value="prev" aria-label="previous" id="prev" class="carousel-button">&laquo;</button>
    <span class="dashboard__announcements__controls__status">
      <%= _('<span class="current-page">{{current_page}}</span> of ' \
            '<span class="total-pages">{{total_pages}}</span>',
            current_page: 1, total_pages: @announcements.count) %>
    </span>
    <button value="next" id="next" aria-label="next" class="carousel-button">&raquo;</button>
  </fieldset>
</div>

app/views/alaveteli_pro/dashboard/_done_to_dos.html.erb
<div class="dashboard-todo">

    <h2 class="dashboard-todo__title"><%= _("Things to do today") %></h2>
    <div class="dashboard-todo__zero">
      <p><%= _("There's nothing to do right now. Great job!") %></p>
    </div>

</div>  <!-- .dashboard-todo -->

app/views/alaveteli_pro/dashboard/_ga_events.html.erb
<% if flash[:new_pro_user] %>
  <% content_for :ga_pageview do %>
    ga('send', 'pageview', '/alaveteli_pro/welcome');
  <% end %>
<% end %>

app/views/alaveteli_pro/dashboard/_no_to_dos.html.erb
<div class="blank-slate">
  <div class="blank-slate__requests">
    <div class="blank-slate__message">
      <h2><%= _("Get started with your first request") %></h2>
      <p><%= _("From this screen you can see what you need to do next to keep your requests moving forward. Why not start a new request now?") %></p>
      <%= link_to _("Start new request"), new_alaveteli_pro_info_request_path, :class => 'button' %>
    </div>
  </div>
</div>

app/views/alaveteli_pro/dashboard/_projects.html.erb
<ul class="vertical-navigation-menu dashboard-folders ">
  <li class="vertical-navigation-menu__item dashboard-folder dashboard-folder--top-level dashboard-folder--selected">
    <a href="<%= alaveteli_pro_info_requests_path %>" class="vertical-navigation-menu__link dashboard-folder__name">
      <%= _('All requests') %>
      <span class="dashboard-folder__count">
        <%= @user.phase_counts['not_drafts'] %>
      </span>
    </a>
  </li>
  <ul class="vertical-navigation-menu dashboard-sub-folders">
    <% InfoRequest::State.phases.each do |phase| %>
    <li class="vertical-navigation-menu__item dashboard-folder">
      <% if @user.phase_counts[phase[:scope]] > 0 %>
        <a href="<%= alaveteli_pro_info_requests_path('alaveteli_pro_request_filter[filter]' => phase[:scope]) %>" class="vertical-navigation-menu__link dashboard-folder__name">
      <% else %>
        <span class="vertical-navigation-menu__link dashboard-folder__name dashboard-folder__name--disabled">
      <% end %>
        <span class="phase-icon phase-icon--<%= phase[:param] %>"></span>
        <%= phase[:capital_label] %>
        <span class="dashboard-folder__count">
          <%= @user.phase_counts[phase[:scope]] %>
        </span>
      <% if @user.phase_counts[phase[:scope]] > 0 %>
        </a>
      <% else %>
        </span>
      <% end %>
    </li>
    <% end %>
  </ul>
</ul>

<ul class="vertical-navigation-menu dashboard-folders">

  <li class="vertical-navigation-menu__item dashboard-folder dashboard-folder--top-level">
    <% if @user.phase_counts['draft'] > 0 %>
      <a href="<%= alaveteli_pro_info_requests_path('alaveteli_pro_request_filter[filter]' => 'draft') %>" class="vertical-navigation-menu__link dashboard-folder__name">
    <% else %>
      <span class="vertical-navigation-menu__link dashboard-folder__name">
    <% end %>
    <%= _('Drafts') %>
    <span class="dashboard-folder__count">
      <%= @user.phase_counts['draft'] %>
    </span>
    <% if @user.phase_counts['draft'] > 0 %>
      </a>
    <% else %>
      </span>
    <% end %>
  </li>

</ul>

app/views/alaveteli_pro/dashboard/_to_do_item.html.erb
<li class="dashboard-todo__list__item">
  <%= to_do_item.description %>
  <%= link_to(to_do_item.call_to_action, to_do_item.url) %>
</li>

app/views/alaveteli_pro/dashboard/_to_do_list.html.erb
<div class="dashboard-todo">

  <h2 class="dashboard-todo__title"><%= _("Things to do today") %></h2>

  <ul class="dashboard-todo__list">

   <%= render partial: 'to_do_item', collection: @to_do_list.active_items %>

  </ul>

</div>  <!-- .dashboard-todo -->

app/views/alaveteli_pro/dashboard/index.html.erb
<%= render :partial => 'ga_events' %>

<div class="inner-canvas">

  <div class="inner-canvas-header">
    <div class="row">
      <h1><%= _("Your dashboard") %></h1>
    </div>
  </div>

  <div class="inner-canvas-body">
    <div class="row">
      <div class="dashboard-left-column">

        <%= render partial: 'alaveteli_pro/dashboard/projects' %>

      </div> <!-- .dashboard-left-column -->

      <div class="dashboard-right-column">
        <% if @announcements.present? %>
          <%= render partial: 'announcements' %>
        <% end %>

        <% if @to_do_list.active_items.empty? && @user.info_requests.empty? && @user.draft_info_requests.empty? && @user.info_request_batches.empty? && @user.draft_info_request_batches.empty? %>
          <%= render partial: 'no_to_dos' %>
        <% elsif @to_do_list.active_items.empty? %>
          <%= render partial: 'done_to_dos' %>
        <% else %>
          <%= render partial: 'to_do_list' %>
        <% end %>


        <div class="dashboard-activity">
          <h2 class="dashboard-activity__title"><%= _("Activity") %></h2>
          <%= render partial: 'activity_list_item', :collection => @activity_list.current_items %>
          <%= will_paginate WillPaginate::Collection.new(@page, @per_page, @activity_list.events.count) %>

        </div> <!-- .dashboard-activity -->

      </div>  <!-- .dashboard-right-column -->


   </div>
  </div>  <!-- .dashboard-body -->

</div>  <!-- .dashboard -->