config/routes.rb
  match '/body/:url_name/:tag/:view' => 'public_body#show',
        :as => :show_public_body_tag_view,
        :via => :get
  ####

  #### PublicBodyChangeRequest controller
  resource :change_request, :only => [:new, :create], :controller => 'public_body_change_requests'
  match 'change_request/new/:body' => 'public_body_change_requests#new',
        :as => :new_change_request_body,
        :via => :get

  #### Comment controller
  match '/annotate/request/:url_title' => 'comment#new',
        :as => :new_comment,
        :type => 'request',
        :via => [:get, :post]
  ####

  #### Services controller
  match '/country_message' => 'services#other_country_message',
        :as => :other_country_message,
        :via => :get
  match '/hidden_user_explanation' => 'services#hidden_user_explanation',
        :as => :hidden_user_explanation,
        :via => :get
  ####

  #### Track controller
  # /track/ is for setting up an email alert for the item
  # /feed/ is a direct RSS feed of the item
  match '/:feed/request/:url_title' => 'track#track_request',
        :as => :track_request,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/list/:view' => 'track#track_list',
        :as => :track_list,
        :view => nil,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/body/:url_name' => 'track#track_public_body',
        :as => :track_public_body,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/user/:url_name' => 'track#track_user',
        :as => :track_user,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/search/:query_array' => 'track#track_search_query',
        :as => :track_search,
        :feed => /(track|feed)/,
        :constraints => { :query_array => /.*/ },
        :via => :get

  match '/track/update/:track_id' => 'track#update',
        :as => :update,
        :via => [:get, :post]
  match '/track/delete_all_type' => 'track#delete_all_type',
        :as => :delete_all_type,
        :via => :post
  match '/track/feed/:track_id' => 'track#atom_feed',
        :as => :atom_feed,
        :via => :get
  ####

  #### Help controller
  match '/help/unhappy(/:url_title)' => 'help#unhappy',
        :as => :help_unhappy,
        :via => :get
  match '/help/about' => 'help#about',
        :as => :help_about,
        :via => :get
  match '/help/alaveteli' => 'help#alaveteli',
        :as => :help_alaveteli,
        :via => :get
  match '/help/contact' => 'help#contact',
        :as => :help_contact,
        :via => [:get, :post]
  match '/help/officers' => 'help#officers',
        :as => :help_officers,
        :via => :get
  match '/help/requesting' => 'help#requesting',
        :as => :help_requesting,
        :via => :get
  match '/help/privacy' => 'help#privacy',
        :as => :help_privacy,
        :via => :get
  match '/help/api' => 'help#api',
        :as => :help_api,
        :via => :get
  match '/help/credits' => 'help#credits',
        :as => :help_credits,
        :via => :get
  match '/help/:template' => 'help#action',
        :as => :help_general,
        :via => :get,
        :template => /[-_a-z]+/
  match '/help' => 'help#index',
        :via => :get
  ####

  #### Holiday controller
  match '/due_date/:holiday' => 'holiday#due_date',
        :as => :due_date,
        :via => :get
  ####

  #### RequestGame controller
  match '/categorise/play' => 'request_game#play',
        :as => :categorise_play,
        :via => [:get, :post]
  match '/categorise/request/:url_title' => 'request_game#show',
        :as => :categorise_request,
        :via => :get
  match '/categorise/stop' => 'request_game#stop',
        :as => :categorise_stop,
        :via => :post
  ####

  #### Announcement controller
  resources :announcements, :only => [:destroy]
  ####

  #### AdminPublicBody controller
  scope '/admin', :as => 'admin' do
    constraints admin_constraint do
      mount Flipper::UI.app(AlaveteliFeatures.backend) => '/flipper'
    end

    resources :bodies,
    :controller => 'admin_public_body' do
      get 'missing_scheme', :on => :collection
      post 'mass_tag_add', :on => :collection
      get 'import_csv', :on => :collection
      post 'import_csv', :on => :collection
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
    end
  end
  ####

  #### AdminPublicBodyCategory controller
  scope '/admin', :as => 'admin' do
    resources :categories,
      :controller => 'admin_public_body_categories'
  end
  ####

  #### AdminPublicBodyHeading controller
  scope '/admin', :as => 'admin'  do
    resources :headings,
      :controller => 'admin_public_body_headings',
    :except => [:index] do
      post 'reorder', :on => :collection
      post 'reorder_categories', :on => :member
    end
  end
  ####

  #### AdminHoliday controller
  scope '/admin', :as => 'admin' do
    resources :holidays,
      :controller => 'admin_holidays'
  end
  ####

  #### AdminHolidayImports controller
  scope '/admin', :as => 'admin' do
    resources :holiday_imports,
      :controller => 'admin_holiday_imports',
      :only => [:new, :create]
  end
  ####

  #### AdminPublicBodyChangeRequest controller
  scope '/admin', :as => 'admin'  do
    resources :change_requests,
      :controller => 'admin_public_body_change_requests',
      :only => [:edit, :update]
  end
  ####

  #### AdminGeneral controller
  match '/admin' => 'admin_general#index',
        :as => :admin_general_index,
        :via => :get
  match '/admin/timeline' => 'admin_general#timeline',
        :as => :admin_timeline,
        :via => :get
  match '/admin/debug' => 'admin_general#debug',
        :as => :admin_debug,
        :via => :get
  match '/admin/stats' => 'admin_general#stats',
        :as => :admin_stats,
        :via => :get
  ####

  #### AdminRequest controller
  scope '/admin', :as => 'admin' do
    resources :requests,
      :controller => 'admin_request',
    :except => [:new, :create] do
      post 'move', :on => :member
      post 'generate_upload_url', :on => :member
      post 'hide', :on => :member
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
    end
  end
  ####

  #### AdminComment controller
  scope '/admin', :as => 'admin' do
    resources :comments,
      :controller => 'admin_comment',
      :only => [:index, :edit, :update]
  end
  ####

  #### AdminRawEmail controller
  scope '/admin', :as => 'admin' do
    resources :raw_emails,
      :controller => 'admin_raw_email',
      :only => [:show]
  end
  ####

  #### AdminInfoRequestEvent controller
  scope '/admin', :as => 'admin' do
    resources :info_request_events,
      :controller => 'admin_info_request_event',
      :only => [:update]
  end

  #### AdminIncomingMessage controller
  scope '/admin', :as => 'admin' do
    resources :incoming_messages,
      :controller => 'admin_incoming_message',
    :only => [:edit, :update, :destroy] do
      post 'redeliver', :on => :member
    end
    resource :incoming_messages,
      :controller => 'admin_incoming_message',
      :only => [:bulk_destroy] do
        post 'bulk_destroy'
      end
  end
  ####

  #### AdminOutgoingMessage controller
  scope '/admin', :as => 'admin' do
    resources :outgoing_messages,
      :controller => 'admin_outgoing_message',
    :only => [:edit, :update, :destroy] do
      post 'resend', :on => :member
    end
  end
  ####

  #### AdminUser controller
  scope '/admin', :as => 'admin' do
    resources :users,
      :controller => 'admin_user',
    :except => [:new, :create, :destroy] do
      get 'banned', :on => :collection
      get 'show_bounce_message', :on => :member
      post 'clear_bounce', :on => :member
      post 'clear_profile_photo', :on => :member
      post 'modify_comment_visibility', :on => :collection
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
      end
  end
  ####

  #### AdminUsersAccountSuspensions controller
  scope '/admin', :as => 'admin' do
    resources :users_account_suspensions,
      :controller => 'admin_users_account_suspensions',
      :only => [:create]
  end
  ####

  #### AdminUsersSessions controller
  scope '/admin', :as => 'admin' do
    resources :users_sessions,
      :controller => 'admin_users_sessions',
      :only => [:create]
  end
  ####

  #### AdminTrack controller
  scope '/admin', :as => 'admin' do
    resources :tracks,
      :controller => 'admin_track',
      :only => [:index, :destroy]
  end
  ####

  #### AdminCensorRule controller
  scope '/admin', :as => 'admin' do
    resources :censor_rules,
      :controller => 'admin_censor_rule'
  end

  #### AdminSpamAddresses controller
  scope '/admin', :as => 'admin' do
    resources :spam_addresses,
      :controller => 'admin_spam_addresses',
      :only => [:index, :create, :destroy]
  end
  ####

  #### AdminAnnouncement controller
  scope '/admin', :as => 'admin' do
    resources :announcements, :controller => 'admin_announcements'
  end
  ####

  #### Api controller
  match '/api/v2/request.json' => 'api#create_request',
        :as => :api_create_request,
        :via => :post

  match '/api/v2/request/:id.json' => 'api#show_request',
        :as => :api_show_request,
        :via => :get
  match '/api/v2/request/:id.json' => 'api#add_correspondence',
        :as => :api_add_correspondence,
        :via => :post
  match '/api/v2/request/:id/update.json' => 'api#update_state',
        :as => :api_update_state,
        :via => :post

  match '/api/v2/body/:id/request_events.:feed_type' => 'api#body_request_events',
        :as => :api_body_request_events,
        :feed_type => '^(json|atom)$',
        :via => :get
  ####

  #### Pro Pricing
  constraints FeatureConstraint.new(:pro_pricing) do

    namespace :alaveteli_pro, path: :pro, as: :pro do
      resources :plans, only: [:index], path: :pricing

app/controllers/request_game_controller.rb
# -*- encoding : utf-8 -*-
# app/controllers/request_game_controller.rb:
# The 'categorise old requests' game
#
# Copyright (c) 2009 UK Citizens Online Democracy. All rights reserved.
# Email: hello@mysociety.org; WWW: http://www.mysociety.org/

class RequestGameController < ApplicationController

  def play
    session[:request_game] = Time.zone.now

    @missing = InfoRequest.
      where_old_unclassified.
        is_searchable.
          count
    @total = InfoRequest.count
    @done = @total - @missing
    @percentage = if @total > 0
      (@done.to_f / @total.to_f * 10000).round / 100.0
    else
      100.0
    end
    @requests = InfoRequest.
      includes(:public_body, :user).
        where_old_unclassified.
          limit(3).
            is_searchable.
              order('random()')

    if @missing == 0
      flash.now[:notice] = {
        :partial => "request_game/game_over.html.erb",
        :locals => {
          :helpus_url => help_credits_path(:anchor => "helpus"),
          :site_name => site_name
        }
      }
    end

    @league_table_28_days = RequestClassification.league_table(10,
      [ "created_at >= ?", Time.zone.now - 28.days ])
    @league_table_all_time = RequestClassification.league_table(10)
    @play_urls = true
  end

  def show
    url_title = params[:url_title]
    if !authenticated?(
        :web => _("To play the request categorisation game"),
        :email => _("Then you can play the request categorisation game."),
        :email_subject => _("Play the request categorisation game")
      )
      # do nothing - as "authenticated?" has done the redirect to signin page for us
      return
    end
    redirect_to show_request_url(:url_title => url_title)
  end

  def stop
    session[:request_game] = nil
    flash[:notice] = _('Thank you for helping us keep the site tidy!')
    redirect_to frontpage_url
  end

end

app/views/request_game/_game_over.html.erb
<%= _('<p>All done! Thank you very much for your help.</p><p>There are ' \
  '<a href="{{helpus_url}}">more things you can do</a> to help ' \
  '{{site_name}}.</p>',
  :helpus_url => helpus_url,
  :site_name => site_name) %>

app/views/request_game/_thank_you.html.erb
<%= _("Thank you for updating the status of the request " \
      "'<a href=\"{{url}}\">{{info_request_title}}</a>'. " \
      "There are some more requests below for you to classify.",
      :info_request_title => info_request_title,
      :url => url) %>

app/views/request_game/play.html.erb
<% @title = _("Play the request categorisation game!") %>

<div id="game_sidebar" class="game_sidebar">
  <p style="text-align: center">
    <%= image_tag "https://chart.googleapis.com/chart?chs=250x125&cht=gom&chd=t:#{@percentage}",
          :size => "250x125",
          :alt => "A chart showing #{@percentage}% of requests have been categorised",
          :title => "#{@percentage}% of requests have been categorised" %>
    <br><%= n_("{{number_of_requests}} request left to categorise / {{total_number_of_requests}} total",
               "{{number_of_requests}} requests left to categorise / {{total_number_of_requests}} total",
               @missing,
               :number_of_requests => number_with_delimiter(@missing),
               :total_number_of_requests => number_with_delimiter(@total)) %>
  </p>

  <h2><%= _("Top recent players") %></h2>
  <table>
    <% @league_table_28_days.each_with_index do |classifications, index| %>
      <tr>
        <td> <%= index += 1 %>. </td>
        <td> <%= user_link(classifications.user) %> </td>
        <td>

        <%= n_("{{number_of_requests}} request",
               "{{number_of_requests}} requests",
               classifications.cnt,
               :number_of_requests => classifications.cnt) %> </td>
      </tr>
    <% end %>
  </table>

  <h2><%= _("All time best players") %></h2>
  <table>
    <% @league_table_all_time.each_with_index do |classifications, index| %>
      <tr>
        <td> <%= index += 1 %>. </td>
        <td> <%= user_link(classifications.user) %> </td>
        <td> <%= n_("{{number_of_requests}} request",
                    "{{number_of_requests}} requests",
                    classifications.cnt,
                    :number_of_requests => classifications.cnt) %> </td>
      </tr>
    <% end %>
  </table>
</div>

<div id="game">
  <h2><%= _("Play the request categorisation game!")%></h2>

  <p>
    <%= _("Some people who've made requests haven't let us know whether " \
          "they were successful or not.  We need <strong>your</strong> help " \
          "&ndash; choose one of these requests, read it, and let everyone " \
          "know whether or not the information has been provided. " \
          "Everyone'll be exceedingly grateful.")%>
  </p>

  <% @requests.each do |info_request| %>
    <%= render :partial => 'request/request_listing_single',
               :locals => { :info_request => info_request } %>
  <% end %>

  <p id="game_buttons">
    <%= button_to _("I don't like these ones &mdash; give me some more!"), categorise_play_url %>
    <%= button_to _("I don't want to do any more tidying now!"), categorise_stop_url %>
  </p>

  <p>
    <%= _("Thanks for helping - your work will make it easier for everyone " \
          "to find successful responses, and maybe even let us make league " \
          "tables...") %>
  </p>
</div>