config/routes.rb
        :via => :get
  match '/list' => 'request#list',
        :as => :request_list,
        :via => :get

  match '/select_authority' => 'request#select_authority',
        :as => :select_authority,
        :via => :get
  match '/select_authorities' => 'request#select_authorities',
        :as => :select_authorities,
        :via => [:get, :post]

  match '/new' => 'request#new',
        :as => :new_request,
        :via => [:get, :post]
  match '/new/:url_name' => 'request#new',
        :as => :new_request_to_body,
        :via => [:get, :post]
  match '/new_batch' => 'request#new_batch',
        :as => :new_batch,
        :via => [:get, :post]

  match '/request/search_ahead' => 'request#search_typeahead',
        :as => :search_ahead,
        :via => :get

  match '/request/:url_title' => 'request#show',
        :as => :show_request,
        :via => :get
  match '/request/:url_title/new' => 'request#show',
        :as => :show_new_request,
        :via => :get
  match '/details/request/:url_title' => 'request#details',
        :as => :details_request,
        :via => :get
  match '/similar/request/:url_title' => 'request#similar',
        :as => :similar_request,
        :via => :get

  match '/request/:id/describe' => 'request#describe_state',
        :as => :describe_state,
        :via => [:patch, :put, :post]
  match '/request/:url_title/describe/:described_state' => 'request#describe_state_message',
        :as => :describe_state_message,
        :via => :get
  match '/request/:id/response/:incoming_message_id/attach/html/:part/*file_name' => 'request#get_attachment_as_html',
        :format => false,
        :as => :get_attachment_as_html,
        :via => :get
  match '/request/:id/response/:incoming_message_id/attach/:part(/*file_name)' => 'request#get_attachment',
        :format => false,
        :as => :get_attachment,
        :via => :get

  match '/request_event/:info_request_event_id' => 'request#show_request_event',
        :as => :info_request_event,
        :via => :get

  match '/upload/request/:url_title' => 'request#upload_response',
        :as => :upload_response,
        :via => [:get, :post]
  match '/request/:url_title/download' => 'request#download_entire_request',
        :as => :download_entire_request,
        :via => :get
  ####

  #### Followups controller
  match '/request/:request_id/followups/new' => 'followups#new',
        :as => :new_request_followup,
        :via => :get
  match '/request/:request_id/followups/new/:incoming_message_id' => 'followups#new',
        :as => :new_request_incoming_followup,
        :via => :get
  match '/request/:request_id/followups/preview' => 'followups#preview',
        :as => :preview_request_followups,
        :via => :post
  match '/request/:request_id/followups' => 'followups#create',
        :as => :request_followups,
        :via => :post
  ####

  resources :health_checks, :only => [:index]

  resources :request, :only => [] do
    resource :report, :only => [:new, :create]
    resource :widget, :only => [:new, :show]
    resources :widget_votes, :only => [:create]
  end

  resources :info_request_batch, :only => :show

  #### OutgoingMessage controller
  resources :outgoing_messages, :only => [] do
    resource :delivery_status, :only => [:show], :module => 'outgoing_messages'
  end
  ####

  #### User controller
  # Use /profile for things to do with the currently signed in user.
  # Use /user/XXXX for things that anyone can see about that user.
  # Note that /profile isn't indexed by search (see robots.txt)
  resources :password_changes,
            :only => [:new, :create, :edit, :update],
            :path => '/profile/change_password',
            :path_names => { :edit => '' }

  resource :one_time_password,
           :only => [:show, :create, :update, :destroy],
           :path => '/profile/two_factor'

  match '/profile/sign_in' => 'users/sessions#new',
        :as => :signin,
        :via => :get
  match '/profile/sign_in' => 'users/sessions#create',
        :as => :create_session,
        :via => :post
  match '/profile/sign_out' => 'users/sessions#destroy',
        :as => :signout,
        :via => :get
  match '/profile/sign_up' => 'user#signup',
        :as => :signup, :via => :post
  match '/c/:email_token' => 'users/confirmations#confirm',
        :as => :confirm,
        :via => :get
  match '/user/:url_name' => 'user#show',
        :as => :show_user,
        :via => :get
  match '/user/:url_name/profile' => 'user#show',
        :as => :show_user_profile,
        :view => 'profile',
        :via => :get
  match '/user/:url_name/requests' => 'user#show',
        :as => :show_user_requests,
        :view => 'requests',
        :via => :get
  match '/user/:url_name/wall' => 'user#wall',
        :as => :show_user_wall,
        :via => :get
  match '/user/contact/:url_name' => 'users/messages#contact',
        :as => :contact_user,
        :via => [:get, :post]
  match '/profile/change_email' => 'user#signchangeemail',
        :as => :signchangeemail,
        :via => [:get, :post]
  match '/profile/set_photo' => 'user#set_profile_photo',
        :as => :set_profile_photo,
        :via => [:get, :post]
  match '/profile/clear_photo' => 'user#clear_profile_photo',
        :as => :clear_profile_photo,
        :via => :post
  match '/user/:url_name/photo.png' => 'user#get_profile_photo',
        :as => :get_profile_photo,
        :via => :get
  match '/profile/draft_photo/:id.png' => 'user#get_draft_profile_photo',
        :as => :get_draft_profile_photo,
        :via => :get

  namespace :users do
    get 'email_alerts/disable/:token',
        to: 'email_alerts#destroy',
        as: :disable_email_alerts
  end

  namespace :profile, :module => 'user_profile' do
    resource :about_me, :only => [:edit, :update], :controller => 'about_me'
  end

  # Legacy route for setting about_me
  match '/profile/set_about_me' => redirect('/profile/about_me/edit'),
        :as => :set_profile_about_me,
        :via => [:get, :post]

  match '/profile/set_receive_alerts' => 'user#set_receive_email_alerts',
        :as => :set_receive_email_alerts,
        :via => [:get, :post]

  match '/profile/river' => 'user#river',
        :as => :river,
        :via => :get
  ####

  #### PublicBody controller
  match '/body/search_ahead' => 'public_body#search_typeahead',
        :as => :search_ahead_bodies,
        :via => :get
  match '/body' => 'public_body#list',
        :as => :list_public_bodies,
        :via => :get
  match '/body/list/all' => 'public_body#list',
        :as => :list_public_bodies_default,
        :via => :get
  match '/body/list/:tag' => 'public_body#list',
        :as => :list_public_bodies_by_tag,
        :via => :get
  match '/local/:tag' => 'public_body#list_redirect',
        :as => :list_public_bodies_redirect,
        :via => :get
  match '/body/all-authorities.csv' => 'public_body#list_all_csv',
        :as => :all_public_bodies_csv,
        :via => :get
  match '/body/:url_name' => 'public_body#show',
        :as => :show_public_body, :view => 'all',
        :via => :get
  match '/body/:url_name/all' => 'public_body#show',
        :as => :show_public_body_all,
        :view => 'all',
        :via => :get
  match '/body/:url_name/successful' => 'public_body#show',
        :as => :show_public_body_successful,
        :view => 'successful',
        :via => :get
  match '/body/:url_name/unsuccessful' => 'public_body#show',
        :as => :show_public_body_unsuccessful,
        :view => 'unsuccessful',
        :via => :get
  match '/body/:url_name/awaiting' => 'public_body#show',
        :as => :show_public_body_awaiting,
        :view => 'awaiting',
        :via => :get
  match '/body/:url_name/view_email' => 'public_body#view_email',
        :as => :view_public_body_email,
        :via => [:get, :post]
  match '/body/:url_name/:tag' => 'public_body#show',
        :as => :show_public_body_tag,
        :via => :get
  match '/body/:url_name/:tag/:view' => 'public_body#show',
        :as => :show_public_body_tag_view,
        :via => :get
  ####

  #### PublicBodyChangeRequest controller
  resource :change_request, :only => [:new, :create], :controller => 'public_body_change_requests'
  match 'change_request/new/:body' => 'public_body_change_requests#new',
        :as => :new_change_request_body,
        :via => :get

  #### Comment controller
  match '/annotate/request/:url_title' => 'comment#new',
        :as => :new_comment,
        :type => 'request',
        :via => [:get, :post]
  ####

  #### Services controller
  match '/country_message' => 'services#other_country_message',
        :as => :other_country_message,
        :via => :get
  match '/hidden_user_explanation' => 'services#hidden_user_explanation',
        :as => :hidden_user_explanation,
        :via => :get
  ####

  #### Track controller
  # /track/ is for setting up an email alert for the item
  # /feed/ is a direct RSS feed of the item
  match '/:feed/request/:url_title' => 'track#track_request',
        :as => :track_request,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/list/:view' => 'track#track_list',
        :as => :track_list,
        :view => nil,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/body/:url_name' => 'track#track_public_body',
        :as => :track_public_body,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/user/:url_name' => 'track#track_user',
        :as => :track_user,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/search/:query_array' => 'track#track_search_query',
        :as => :track_search,
        :feed => /(track|feed)/,
        :constraints => { :query_array => /.*/ },
        :via => :get

  match '/track/update/:track_id' => 'track#update',
        :as => :update,
        :via => [:get, :post]
  match '/track/delete_all_type' => 'track#delete_all_type',
        :as => :delete_all_type,
        :via => :post

app/models/user/with_request.rb
class User::WithRequest < SimpleDelegator
  attr_reader :request

  delegate :user_agent, to: :request

  def initialize(user, request)
    @request = request
    super(user)
  end
end

app/controllers/users/confirmations_controller.rb
# -*- encoding : utf-8 -*-
class Users::ConfirmationsController < UserController

  def confirm
    post_redirect = PostRedirect.find_by_email_token(params[:email_token])

    if post_redirect.nil?
      render :template => 'user/bad_token'
      return
    end

    case post_redirect.circumstance
    when 'change_password'
      unless session[:user_id] == post_redirect.user_id
        clear_session_credentials
      end

      redirect_to SafeRedirect.new(post_redirect.uri).path
      return

    when 'normal', 'change_email'
      # !User.stay_logged_in_on_redirect?(nil)
      # # => true
      # !User.stay_logged_in_on_redirect?(user)
      # # => true
      # !User.stay_logged_in_on_redirect?(admin)
      # # => false
      if User.stay_logged_in_on_redirect?(@user)
        session[:admin_confirmation] = 1
      else
        @user = confirm_user!(post_redirect.user)
      end

      session[:user_id] = @user.id
    end

    session[:user_circumstance] = post_redirect.circumstance
    do_post_redirect post_redirect, @user
  end

  private

  def confirm_user!(user)
    user.confirm!
    user
  end

end

app/controllers/users/email_alerts_controller.rb
# -*- encoding : utf-8 -*-
# Managing a User's email alerts.
class Users::EmailAlertsController < ApplicationController
  def destroy
    unless User::EmailAlerts.disable_by_token(CGI.unescape(params[:token]))
      redirect_to root_path, flash: { error: _('Invalid token') }
    end
  end
end

app/controllers/users/messages_controller.rb
# -*- encoding : utf-8 -*-
# Allowing users to send user-to-user messages
class Users::MessagesController < UserController

  before_action :set_recipient, :check_can_send_messages, :check_logged_in,
                :set_contact, :set_recaptcha_required

  # Send a message to another user
  def contact
    return unless params[:submitted_contact_form]

    if @recaptcha_required && !verify_recaptcha
      flash.now[:error] = _('There was an error with the reCAPTCHA. ' \
                            'Please try again.')
    else
      if @contact.valid?
        send_message(@user, @recipient_user)
        flash[:notice] = _('Your message to {{recipient_user_name}} has ' \
                           'been sent!',
                           recipient_user_name: @recipient_user.name.html_safe)
        redirect_to user_url(@recipient_user)
      end
    end
  end

  private

  def set_recipient
    @recipient_user = User.find_by!(url_name: params[:url_name])
  end

  def check_can_send_messages
    # Banned from messaging users?
    if authenticated_user && !authenticated_user.can_contact_other_users?
      @details = authenticated_user.can_fail_html
      render template: 'user/banned'
      return
    end
  end

  def check_logged_in
    # You *must* be logged into send a message to another user. (This is
    # partly to avoid spam, and partly to have some equanimity of openess
    # between the two users)
    #
    # "authenticated?" has done the redirect to signin page for us
    return unless authenticated?(
      web: _('To send a message to {{user_name}}',
             user_name: CGI.escapeHTML(@recipient_user.name)),
      email: _('Then you can send a message to {{user_name}}.',
               user_name: @recipient_user.name),
      email_subject: _('Send a message to {{user_name}}',
                       user_name: @recipient_user.name)
    )
  end

  def set_contact
    if params[:submitted_contact_form]
      params[:contact][:name] = @user.name
      params[:contact][:email] = @user.email
      @contact = ContactValidator.new(params[:contact])
    else
      @contact = ContactValidator.new(
        message: '' + @recipient_user.name +
                 _(",\n\n\n\nYours,\n\n{{user_name}}", user_name: @user.name)
      )
    end
  end

  def set_recaptcha_required
    @recaptcha_required = AlaveteliConfiguration.user_contact_form_recaptcha
  end

  def send_message(sender, recipient)
    ContactMailer.user_message(
      sender,
      recipient,
      user_url(sender),
      params[:contact][:subject],
      params[:contact][:message]
    ).deliver_now
  end

end

app/controllers/users/sessions_controller.rb
# -*- encoding : utf-8 -*-
class Users::SessionsController < UserController
  include UserSpamCheck

  before_action :work_out_post_redirect, :only => [ :new, :create ]
  before_action :set_request_from_foreign_country, :only => [ :new, :create ]
  before_action :set_in_pro_area, :only => [ :new, :create ]

  # Normally we wouldn't be verifying the authenticity token on these actions
  # anyway as there shouldn't be a user_id in the session when the before
  # filter run. This skip handles cases where an already logged in user
  # tries to sign in or sign up. There's little CSRF potential here as
  # these actions only sign in or up users with valid credentials. The
  # user_id in the session is not expected, and gives no extra privilege
  skip_before_action :verify_authenticity_token, :only => [:new, :create]

  def new
    if @user
      redirect_path = params.fetch(:r) { frontpage_path }
      redirect_to SafeRedirect.new(redirect_path).path
      return
    end

    render :template => 'user/sign'
  end

  def create
    if @post_redirect.present?
      @user_signin =
        User.authenticate_from_form(user_signin_params,
                                    @post_redirect.reason_params[:user_name])
    end
    if @post_redirect.nil? || @user_signin.errors.size > 0
      # Failed to authenticate
      clear_session_credentials
      render :template => 'user/sign'
    else
      # Successful login
      if @user_signin.email_confirmed

        # Prevent signins from potential spammers
        if spam_user?(@user_signin)
          handle_spam_user(@user_signin) do
            render template: 'user/sign'
          end && return
        end

        session[:user_id] = @user_signin.id
        session[:ttl] = nil
        session[:user_circumstance] = nil
        session[:remember_me] = params[:remember_me] ? true : false

        if is_modal_dialog
          render :template => 'users/sessions/show'
        else
          do_post_redirect @post_redirect, @user_signin
        end
      else
        send_confirmation_mail @user_signin
      end
    end
  end

  def destroy
    clear_session_credentials
    redirect_path = params.fetch(:r) { frontpage_path }
    redirect_to SafeRedirect.new(redirect_path).path
  end

  private

  def user_signin_params
    params.require(:user_signin).permit(:email, :password)
  end

  def spam_should_be_blocked?
    AlaveteliConfiguration.block_spam_signins ||
      AlaveteliConfiguration.enable_anti_spam
  end

end

app/views/user/_signin.html.erb
<div id="signin" class="signin">
  <%= form_tag(signin_path, {:id => "signin_form"}) do %>
    <%= foi_error_messages_for :user_signin %>

    <p>
      <label class="form_label" for="user_signin_email"><%= _('Your e-mail:') %></label>
      <%= text_field 'user_signin', 'email', { :size => 20, :tabindex => 60 } %>
    </p>

    <p>
      <label class="form_label" for="user_signin_password"><%= _('Password:') %></label>
      <%= password_field 'user_signin', 'password', { :size => 15, :tabindex => 70, :autocomplete => 'off' } %>
    </p>

    <p class="form_note">
      <%= link_to _('Forgotten your password?'), new_password_change_path(:pretoken => h(params[:token])), :tabindex => 80 %>
    </p>

    <p class="form_checkbox">
      <%= check_box_tag 'remember_me', "1", false, :tabindex => 90 %>

      <label for="remember_me">
        <%= _('Remember me (keeps you signed in longer; do not use on a public computer)') %>
      </label>
    </p>

    <div class="form_button">
      <%= hidden_field_tag 'token', params[:token], {:id => 'signin_token' } %>
      <%= hidden_field_tag :modal, params[:modal], {:id => 'signin_modal' } %>
      <%= submit_tag _('Sign in'), :tabindex => 100 %>
    </div>
  <% end %>
</div>

app/views/user/_update_profile_text.html.erb
<%= _("<p>Thanks for changing the text about you on your " \
      "profile.</p><p><strong>Next...</strong> You can " \
      "upload a profile photograph too.</p>") %>

app/views/user/_user_listing_single.html.erb
<% if @highlight_words.nil? %>
  <% @highlight_words = [] %>
<% end %>

<div class="user_listing">
  <% if display_user.profile_photo %>
    <div class="user_photo_on_search">
      <a href="<%=user_path(display_user)%>">
        <img src="<%= get_profile_photo_url(:url_name => display_user.url_name) %>" alt="">
      </a>
    </div>
  <% end %>

  <span class="head <% if display_user.profile_photo %>no_icon<% end %>">
    <%= link_to highlight_words(display_user.name, @highlight_words), user_path(display_user) %>
  </span>

  <span class="bottomline">
    <% request_count = display_user.info_requests.is_public.size %>
    <%= n_('{{count}} request made.',
           '{{count}} requests made.',
           request_count,
           :count => request_count) %>
    <% if feature_enabled?(:annotations) %>
      <% annotation_count = display_user.comments.visible.size %>
      <%= n_('{{count}} annotation made.',
             '{{count}} annotations made.',
             annotation_count,
             :count => annotation_count) %>
    <% end %>

    <%= _('Joined in {{year}}.', :year => display_user.created_at.year) %>
  </span>
</div>

app/views/user/banned.html.erb
<% @title = _("Banned from this site") %>

<h1><%= @title %></h1>

<p>
  <%= @details %>
</p>

<% if feature_enabled?(:annotations) %>
  <p>
    <%= _('You will be unable to make new requests, send follow ups, add ' \
          'annotations or send messages to other users. You may continue ' \
          'to view other requests, and set up email alerts.') %>
  </p>
<% else %>
  <p>
    <%= _('You will be unable to make new requests, send follow ups ' \
          'or send messages to other users. You may continue ' \
          'to view other requests, and set up email alerts.') %>
  </p>
<% end %>
<p>
  <%= _('If you would like us to lift this ban, then you may politely' \
        '<a href="/help/contact">contact us</a> giving reasons.') %>
</p>

app/views/user/confirm.html.erb
<% @title = _("Now check your email!") %>

<h1 class="confirmation_heading"><%= _("Now check your email!") %></h1>

<p class="confirmation_message">
<%= _("We've sent you an email, and you'll need to click the link in it " \
      "before you can continue.") %>
</p>

<p class="confirmation_message">
  <small>
    <%= _('If you use web-based email or have "junk mail" filters, also ' \
          'check your bulk/spam mail folders. Sometimes, our messages are ' \
          'marked that way.') %>
  </small>
</p>

app/views/user/contact.html.erb
<% @title = _("Contact {{recipient}}", :recipient => h(@recipient_user.name)) %>

<% if not @user %>
  <% raise "You need to be logged in" %>
<% end %>

<%= foi_error_messages_for :contact %>

<%= form_for :contact do |f| %>
  <div class="form_note">
    <h1><%= _("Contact {{recipient}}", :recipient => h(@recipient_user.name)) %></h1>
  </div>

  <p>
    <label class="form_label"><%= _("From") %>:</label>
    <%= h(@user.name_and_email) %>
  </p>

  <p>
    <label class="form_label" for="contact_subject"><%= _("Subject") %>:</label>
    <%= f.text_field :subject, :size => 50 %>
  </p>

  <p>
    <label class="form_label" for="contact_message"><%= _("Message") %>:</label>
    <%= f.text_area :message, :rows => 10, :cols => 50 %>
  </p>

  <p class="form_note">
    <% if @user == @recipient_user %>
      <%= _("<strong>Note:</strong> You're sending a message to yourself, " \
            "presumably to try out how it works.")%>
    <% else %>
      <%= _(' <strong>Privacy note:</strong> Your email address will be given to') %>
      <%= user_link(@recipient_user) %><%= _(' when you send this message.')%>
    <% end %>
  </p>

  <% if @recaptcha_required %>
    <%= recaptcha_tags %><br />
  <% end %>

  <div class="form_button">
    <%= hidden_field_tag(:submitted_contact_form, { :value => 1 } ) %>
    <%= submit_tag _("Send message") %>
  </div>
<% end %>

app/views/user/no_cookies.html.erb
<% @title = _("Cookies not enabled") %>

<h1><%= _('Please enable "cookies" to carry on') %></h1>

<p><%= _('To carry on, you need to sign in or make an account. ' \
         'Unfortunately, there was a technical problem trying to ' \
         'do this.') %></p>

<p><%= _('It may be that your browser is not set to accept a thing called ' \
         '"cookies", or cannot do so.  If you can, please enable cookies, ' \
         'or try using a different browser.  Then press refresh to have ' \
         'another go.') %></p>

<p><%= _('If your browser is set to accept cookies and you are seeing this ' \
         'message, then there is probably a fault with our server.') %>

<%= _('Please <a href="{{url}}">get in touch</a> with us so we can fix it.',
      :url => help_contact_path.html_safe) %>

<%= _('Let us know what you were doing when this message ' \
      'appeared and your browser and operating system type and version.') %>
</p>

<p><%= _('If you are still having trouble, please <a href="{{url}}">' \
         'contact us</a>.', :url => help_contact_path.html_safe) %>
</p>

app/views/user/set_crop_profile_photo.html.erb
<% @title = _("Change profile photo") %>
<% content_for :javascript do %>
  <%= javascript_include_tag "profile-photos" %>
  <%= stylesheet_link_tag "jquery.Jcrop.min.css" %>
<% end %>

<% raise "internal error" if not @user %>

<h2><%= _('Crop your profile photo') %></h2>

<%= foi_error_messages_for :set_profile_photo %>

<div id="set_crop_profile_photo" class="set_crop_profile_photo">
  <%= form_tag 'set_photo', :id => 'set_crop_profile_photo_form', :multipart => true do %>
    <table>
      <tr>
        <td>
          <img src="<%= get_draft_profile_photo_url(:id => @draft_profile_photo.id) %>" id="profile_photo_cropbox">
        </td>
        <td>
          <div style="width:96px;height:96px;overflow:hidden;">
            <img src="<%= get_draft_profile_photo_url(:id => @draft_profile_photo.id) %>" id="profile_photo_preview" class="jcrop-preview" />
          </div>
        </td>
      </tr>
    </table>

    <input type="hidden" id="x" name="x" >
    <input type="hidden" id="y" name="y" >
    <input type="hidden" id="w" name="w" >
    <input type="hidden" id="h" name="h" >

    <%= hidden_field_tag 'draft_profile_photo_id', @draft_profile_photo.id %>

    <p>
      <%= _('<strong>Privacy note:</strong> Your photo will be shown in ' \
            'public on the Internet, wherever you do something on {{site_name}}.',
            :site_name => site_name) %>
    </p>

    <p>
      <%= hidden_field_tag 'submitted_crop_profile_photo', 1 %>
      <%= submit_tag _("Done &gt;&gt;") %>
    </p>
  <% end %>
</div>

app/views/user/show.html.erb
<% if @show_requests %>
  <% @title =  _("{{user_name}} - Freedom of Information requests",
                 :user_name => h(@display_user.name)) %>
<% else %>
  <% @title = _("{{user_name}} - user profile",
                :user_name => h(@display_user.name)) %>
<% end %>

<% if @same_name_users.size >= 1 %>
  <%= render partial: 'user/show/show_same_name_users' %>
<% end %>

<% if @show_profile && @is_you && @undescribed_requests.size > 0 %>
  <%= render partial: 'user/show/show_undescribed_requests' %>
<% end %>

<% if @show_profile %>
  <%= render partial: 'user/show/show_profile' %>
<% end %>

<% if @show_batches %>
  <%= render partial: 'user/show/show_batches' %>
<% end %>

<% if @show_requests %>
  <%= render partial: 'user/show/show_requests' %>
<% end %>

<% if @show_profile && @is_you %>
  <h2 id="email_subscriptions" class="email_subscriptions">
    <%= _("Things you're following") %>
  </h2>

  <%= render :partial => 'change_receive_email' %>

  <br>

  <%= render partial: 'user/show/show_track_things' %>
<% end %>

app/views/user/sign.html.erb
<% if !@post_redirect.nil? && @post_redirect.reason_params[:user_name] %>
  <% @title = _("Sign in") %>
  <div id="sign_alone" class="sign_alone">

    <p id="sign_in_reason" class="sign_in_reason">
      <% if @post_redirect.reason_params[:web].empty? %>
        <%= _('Please sign in as {{user_name}}',
              :user_name => link_to(
                              h(@post_redirect.reason_params[:user_name]),
                              @post_redirect.reason_params[:user_url])) %>
      <% else %>
        <%= _('{{reason}}, please sign in as {{user_name}}.',
              :reason => @post_redirect.reason_params[:web],
              :user_name => link_to(
                              h(@post_redirect.reason_params[:user_name]),
                              @post_redirect.reason_params[:user_url])) %>
      <% end %>
    </p>

    <% if @post_redirect.post_params["controller"] == "admin_general" %>
      <% unless AlaveteliConfiguration::disable_emergency_user %>
        <p id="superuser_message" class="superuser_message">
          <%= _("Don't have a superuser account yet?") %>
          <%= link_to _("Sign in as the emergency user"),
                      SafeRedirect.new(@post_redirect.uri).path(query: 'emergency=1') %>
        </p>
      <% end %>
    <% end %>

    <%= render :partial => 'signin', :locals => { :sign_in_as_existing_user => true } %>
  </div>
<% else %>
  <% @title = _('Sign in or make a new account') %>

  <div id="sign_together" class="sign_together">
    <% if !@post_redirect.nil? %>
      <h1 id="sign_in_reason" class="sign_in_reason">
        <% if @post_redirect.reason_params[:web].empty? %>
          <%= _('Please create an account or sign in') %>
        <% else %>
          <%= _('{{reason}}, create an account or sign in',
          :reason => @post_redirect.reason_params[:web]) %>
        <% end %>
      </h1>
    <% end %>
    <div id="left_half" class="left_half">
      <h2><%= _('Create a new account') %></h2>
      <%= render :partial => 'signup' %>
    </div>

    <div id="right_half" class="right_half">
      <div class="sign-in-wrapper">
        <p class="pretitle">
        <% if !@post_redirect.nil? && @post_redirect.reason_params[:pro] %>
          <%= _('Got a {{site_name}} account?', :site_name => site_name) %>
        <% else %>
          <%= _('Got an account?') %>
        <% end %>
        </p>
        <h2><%= _('Sign in') %></h2>
        <%= render :partial => 'signin', :locals => { :sign_in_as_existing_user => false } %>
      </div>
    </div>

    <div style="clear:both"></div>
  </div>
<% end %>

app/views/user/wrong_user.html.erb
<p id="sign_in_reason" class="sign_in_reason">
  <%= _('Sorry, but only {{user_name}} is allowed to do that.',
        :user_name => h(@reason_params[:user_name])) %>
</p>