config/routes.rb
  match '/annotate/request/:url_title' => 'comment#new',
        :as => :new_comment,
        :type => 'request',
        :via => [:get, :post]
  ####

  #### Services controller
  match '/country_message' => 'services#other_country_message',
        :as => :other_country_message,
        :via => :get
  match '/hidden_user_explanation' => 'services#hidden_user_explanation',
        :as => :hidden_user_explanation,
        :via => :get
  ####

  #### Track controller
  # /track/ is for setting up an email alert for the item
  # /feed/ is a direct RSS feed of the item
  match '/:feed/request/:url_title' => 'track#track_request',
        :as => :track_request,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/list/:view' => 'track#track_list',
        :as => :track_list,
        :view => nil,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/body/:url_name' => 'track#track_public_body',
        :as => :track_public_body,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/user/:url_name' => 'track#track_user',
        :as => :track_user,
        :feed => /(track|feed)/,
        :via => :get
  match '/:feed/search/:query_array' => 'track#track_search_query',
        :as => :track_search,
        :feed => /(track|feed)/,
        :constraints => { :query_array => /.*/ },
        :via => :get

  match '/track/update/:track_id' => 'track#update',
        :as => :update,
        :via => [:get, :post]
  match '/track/delete_all_type' => 'track#delete_all_type',
        :as => :delete_all_type,
        :via => :post
  match '/track/feed/:track_id' => 'track#atom_feed',
        :as => :atom_feed,
        :via => :get
  ####

  #### Help controller
  match '/help/unhappy(/:url_title)' => 'help#unhappy',
        :as => :help_unhappy,
        :via => :get
  match '/help/about' => 'help#about',
        :as => :help_about,
        :via => :get
  match '/help/alaveteli' => 'help#alaveteli',
        :as => :help_alaveteli,
        :via => :get
  match '/help/contact' => 'help#contact',
        :as => :help_contact,
        :via => [:get, :post]
  match '/help/officers' => 'help#officers',
        :as => :help_officers,
        :via => :get
  match '/help/requesting' => 'help#requesting',
        :as => :help_requesting,
        :via => :get
  match '/help/privacy' => 'help#privacy',
        :as => :help_privacy,
        :via => :get
  match '/help/api' => 'help#api',
        :as => :help_api,
        :via => :get
  match '/help/credits' => 'help#credits',
        :as => :help_credits,
        :via => :get
  match '/help/:template' => 'help#action',
        :as => :help_general,
        :via => :get,
        :template => /[-_a-z]+/
  match '/help' => 'help#index',
        :via => :get
  ####

  #### Holiday controller
  match '/due_date/:holiday' => 'holiday#due_date',
        :as => :due_date,
        :via => :get
  ####

  #### RequestGame controller
  match '/categorise/play' => 'request_game#play',
        :as => :categorise_play,
        :via => [:get, :post]
  match '/categorise/request/:url_title' => 'request_game#show',
        :as => :categorise_request,
        :via => :get
  match '/categorise/stop' => 'request_game#stop',
        :as => :categorise_stop,
        :via => :post
  ####

  #### Announcement controller
  resources :announcements, :only => [:destroy]
  ####

  #### AdminPublicBody controller
  scope '/admin', :as => 'admin' do
    constraints admin_constraint do
      mount Flipper::UI.app(AlaveteliFeatures.backend) => '/flipper'
    end

    resources :bodies,
    :controller => 'admin_public_body' do
      get 'missing_scheme', :on => :collection
      post 'mass_tag_add', :on => :collection
      get 'import_csv', :on => :collection
      post 'import_csv', :on => :collection
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
    end
  end
  ####

  #### AdminPublicBodyCategory controller
  scope '/admin', :as => 'admin' do
    resources :categories,
      :controller => 'admin_public_body_categories'
  end
  ####

  #### AdminPublicBodyHeading controller
  scope '/admin', :as => 'admin'  do
    resources :headings,
      :controller => 'admin_public_body_headings',
    :except => [:index] do
      post 'reorder', :on => :collection
      post 'reorder_categories', :on => :member
    end
  end
  ####

  #### AdminHoliday controller
  scope '/admin', :as => 'admin' do
    resources :holidays,
      :controller => 'admin_holidays'
  end
  ####

  #### AdminHolidayImports controller
  scope '/admin', :as => 'admin' do
    resources :holiday_imports,
      :controller => 'admin_holiday_imports',
      :only => [:new, :create]
  end
  ####

  #### AdminPublicBodyChangeRequest controller
  scope '/admin', :as => 'admin'  do
    resources :change_requests,
      :controller => 'admin_public_body_change_requests',
      :only => [:edit, :update]
  end
  ####

  #### AdminGeneral controller
  match '/admin' => 'admin_general#index',
        :as => :admin_general_index,
        :via => :get
  match '/admin/timeline' => 'admin_general#timeline',
        :as => :admin_timeline,
        :via => :get
  match '/admin/debug' => 'admin_general#debug',
        :as => :admin_debug,
        :via => :get
  match '/admin/stats' => 'admin_general#stats',
        :as => :admin_stats,
        :via => :get
  ####

  #### AdminRequest controller
  scope '/admin', :as => 'admin' do
    resources :requests,
      :controller => 'admin_request',
    :except => [:new, :create] do
      post 'move', :on => :member
      post 'generate_upload_url', :on => :member
      post 'hide', :on => :member
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
    end
  end
  ####

  #### AdminComment controller
  scope '/admin', :as => 'admin' do
    resources :comments,
      :controller => 'admin_comment',
      :only => [:index, :edit, :update]
  end
  ####

  #### AdminRawEmail controller
  scope '/admin', :as => 'admin' do
    resources :raw_emails,
      :controller => 'admin_raw_email',
      :only => [:show]
  end
  ####

  #### AdminInfoRequestEvent controller
  scope '/admin', :as => 'admin' do
    resources :info_request_events,
      :controller => 'admin_info_request_event',
      :only => [:update]
  end

  #### AdminIncomingMessage controller
  scope '/admin', :as => 'admin' do
    resources :incoming_messages,
      :controller => 'admin_incoming_message',
    :only => [:edit, :update, :destroy] do
      post 'redeliver', :on => :member
    end
    resource :incoming_messages,
      :controller => 'admin_incoming_message',
      :only => [:bulk_destroy] do
        post 'bulk_destroy'
      end
  end
  ####

  #### AdminOutgoingMessage controller
  scope '/admin', :as => 'admin' do
    resources :outgoing_messages,
      :controller => 'admin_outgoing_message',
    :only => [:edit, :update, :destroy] do
      post 'resend', :on => :member
    end
  end
  ####

  #### AdminUser controller
  scope '/admin', :as => 'admin' do
    resources :users,
      :controller => 'admin_user',
    :except => [:new, :create, :destroy] do
      get 'banned', :on => :collection
      get 'show_bounce_message', :on => :member
      post 'clear_bounce', :on => :member
      post 'clear_profile_photo', :on => :member
      post 'modify_comment_visibility', :on => :collection
      resources :censor_rules,
        :controller => 'admin_censor_rule',
        :only => [:new, :create]
      end
  end
  ####

  #### AdminUsersAccountSuspensions controller
  scope '/admin', :as => 'admin' do
    resources :users_account_suspensions,
      :controller => 'admin_users_account_suspensions',
      :only => [:create]
  end
  ####

  #### AdminUsersSessions controller
  scope '/admin', :as => 'admin' do
    resources :users_sessions,
      :controller => 'admin_users_sessions',
      :only => [:create]
  end
  ####

  #### AdminTrack controller
  scope '/admin', :as => 'admin' do
    resources :tracks,
      :controller => 'admin_track',
      :only => [:index, :destroy]
  end
  ####

  #### AdminCensorRule controller
  scope '/admin', :as => 'admin' do
    resources :censor_rules,
      :controller => 'admin_censor_rule'
  end

  #### AdminSpamAddresses controller
  scope '/admin', :as => 'admin' do
    resources :spam_addresses,
      :controller => 'admin_spam_addresses',
      :only => [:index, :create, :destroy]
  end
  ####

  #### AdminAnnouncement controller
  scope '/admin', :as => 'admin' do
    resources :announcements, :controller => 'admin_announcements'
  end
  ####

  #### Api controller
  match '/api/v2/request.json' => 'api#create_request',
        :as => :api_create_request,
        :via => :post

  match '/api/v2/request/:id.json' => 'api#show_request',
        :as => :api_show_request,
        :via => :get
  match '/api/v2/request/:id.json' => 'api#add_correspondence',
        :as => :api_add_correspondence,
        :via => :post
  match '/api/v2/request/:id/update.json' => 'api#update_state',
        :as => :api_update_state,
        :via => :post

  match '/api/v2/body/:id/request_events.:feed_type' => 'api#body_request_events',
        :as => :api_body_request_events,
        :feed_type => '^(json|atom)$',
        :via => :get
  ####

  #### Pro Pricing
  constraints FeatureConstraint.new(:pro_pricing) do

    namespace :alaveteli_pro, path: :pro, as: :pro do
      resources :plans, only: [:index], path: :pricing
      resources :pages, only: [:show]
    end

    scope module: :alaveteli_pro do
      resources :plans, only: [:show]

      scope path: :profile do
        resources :subscriptions, only: [:index, :create, :destroy] do
          collection do
            resource :payment_method, only: [:update]
          end
        end
      end

      match '/pro/subscriptions/stripe-webhook' => 'stripe_webhooks#receive',
            :via => :post
    end

  end

app/views/admin_public_body/_form.html.erb
<% if @public_body.errors.any? %>
  <ul>
    <% @public_body.errors.each do |attr, message| %>
      <% unless attr.to_s.starts_with?('translation') %>
        <li><%= message %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<% @public_body.ordered_translations.each do |translation| %>
  <% if translation.errors.any? %>
    <%= locale_name(translation.locale.to_s) || translation.locale.to_s %>
    <ul>
      <% translation.errors.each do |attr, message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<!--[form:public_body]-->

<div id="div-locales">
  <ul class="locales nav nav-tabs">
    <% @public_body.ordered_translations.each do |translation| %>
      <li>
        <a href="#div-locale-<%= translation.locale.to_s %>" data-toggle="tab">
          <%= locale_name(translation.locale.to_s) || translation.locale.to_s %>
        </a>
      </li>
    <% end %>
  </ul>

  <div class="tab-content">
    <% @public_body.ordered_translations.each do |translation| %>
      <% if AlaveteliLocalization.default_locale?(translation.locale) %>
        <%= fields_for('public_body', @public_body) do |t| %>
          <%= render :partial => 'locale_fields', :locals => { :t => t, :locale => translation.locale } %>
        <% end %>
      <% else %>
        <%= f.fields_for(:translations, translation, :child_index => translation.locale) do |t| %>
          <%= render :partial => 'locale_fields' , :locals => { :t => t, :locale => translation.locale } %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<h3>Common Fields</h3>
<div class="control-group">
  <label for="public_body_tag_string" class="control-label"><%=_("Tags")%></label>
  <div class="controls">
    <%= f.text_field :tag_string, :class => "span4" %>
    <div class="help-block">
      <p>Space separated – see list of tags on the right.</p>
      <p>Special tags:</p>
      <ul>
        <li><code>not_apply</code>: if FOI and EIR no longer apply to authority and prevents further requests from being sent</li>
        <li><code>foi_no</code>: if FOI does not apply but the authority is still willing to accept requests</li>
        <li><code>eir_only</code> if EIR but not FOI applies to authority</li>
        <li><code>defunct</code> if the authority no longer exists</li>
        <li><code>charity:NUMBER</code> if a registered charity</li>
        <li><code>important_notes</code> if the notes have major implications on making a request to this authority</li>
      </ul>
    </div>
  </div>
</div>
<div class="control-group">
  <label for="public_body_home_page" class="control-label"><%=_("Home page")%></label>
  <div class="controls">
    <%= f.text_field :home_page, :class => "span4"  %>
    <p class="help-block">(of whole authority, not just their FOI page; set to <strong>blank</strong> (empty string) to guess it from the email)</p>
  </div>
</div>
<div class="control-group">
  <label for="public_body_disclosure_log" class="control-label"><%=_("Disclosure log URL")%></label>
  <div class="controls">
    <%= f.text_field :disclosure_log, :size => 60, :class => "span4" %>
  </div>
</div>
<div class="control-group">
  <label for="public_body_last_edit_comment" class="control-label"><strong>Comment</strong> for this edit</label>
  <div class="controls">
    <%= f.text_area :last_edit_comment, :rows => 3, :class => "span6"  %></p>
  <p class="help-block">put URL or other source of new info</p>
  </div>
</div>
<% if @change_request %>
  <%= render :partial => 'admin_public_body_change_requests/response' %>

<% end %>
<!--[eoform:public_body]-->

app/views/admin_public_body/_locale_fields.html.erb
<div class="tab-pane" id="div-locale-<%= locale %>">
  <div class="control-group">
    <%= t.hidden_field :locale, :value => locale %>
    <%= t.label :name, 'Name', :class => 'control-label' %>
    <div class="controls">
      <%= t.text_field :name, :class => "span4" %>
    </div>
  </div>

  <div class="control-group">
    <%= t.label :short_name, 'Short name', :class => 'control-label' %>
    <div class="controls">
      <%= t.text_field :short_name, :class => "span2"  %>
      <p class="help-block">
        <%=_("Only put in abbreviations which are really used, otherwise leave blank. Short or long name is used in the URL – don't worry about breaking URLs through renaming, as the history is used to redirect")%>
      </p>
    </div>
  </div>

  <div class="control-group">
    <%= t.label :request_email, 'Request email', :class => 'control-label' %>
    <div class="controls">
      <%= t.text_field :request_email, :class => "span3" %>
      <p class="help-block">
        <%=_("set to <strong>blank</strong> (empty string) if can't find an address; these emails are <strong>public</strong> as anyone can view with a CAPTCHA")%>
      </p>

      <% if @public_body.ordered_translations.many? %>
        <div class="alert alert-info">
          <i class="icon-info-sign"></i>
          Make sure you add the request email for <em>all</em> locales that have
          translated attributes.
        </div>
      <% end %>
    </div>
  </div>

  <div class="control-group">
    <%= t.label :publication_scheme, 'Publication scheme URL', :class => 'control-label' %>
    <div class="controls">
      <%= t.text_field :publication_scheme, :size => 60, :class => "span3" %>
    </div>
  </div>

  <div class="control-group">
    <%= t.label :notes, 'Public notes', :class => 'control-label' %>
    <div class="controls">
      <%= t.text_area :notes, :rows => 3, :class => "span6" %>
      <p class="help-block">
        HTML, for users to consider when making FOI requests to the authority
      </p>
    </div>
  </div>

</div>

app/views/admin_public_body/_one_list.html.erb
<div class="accordion" id="bodies">
<% for public_body in bodies %>
  <div class="accordion-group">
    <div class="accordion-heading accordion-toggle row">
      <span class="item-title span6">
        <a href="#body_<%=public_body.id%>" data-toggle="collapse" data-parent="requests"><%= chevron_right %></a>
        <%= link_to(public_body.name, admin_body_path(public_body), :title => "view full details")%>
      </span>
      <span class="item-metadata span6">
        <%= render :partial => 'tags', :locals => { :body => public_body} %>
      </span>
    </div>
    <div id="body_<%=public_body.id%>" class="item-detail accordion-body collapse row">
      <% public_body.for_admin_column do |name, value, type| %>
        <div>
          <span class="span6">
            <b><%=name%></b>
          </span>
          <span class="span6">
            <% if type == 'datetime' %>
              <%= I18n.l(value, :format => "%e %B %Y %H:%M:%S") %>
              (<%= _('{{length_of_time}} ago', :length_of_time => time_ago_in_words(value)) %>)
            <% else %>
              <%= h value %>&nbsp;
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
</div>

<%= form_tag(mass_tag_add_admin_bodies_path, :method => "post", :class => "form form-inline" ) do %>
  <p>
    <%= text_field_tag 'new_tag', params[:new_tag], { :size => 15, :id => "mass_add_tag_new_tag_" + table_name } %>
    <%= hidden_field_tag(:query, params[:query], { :id => "mass_add_tag_query_" + table_name } ) %>
    <%= hidden_field_tag(:page, params[:page], { :id => "mass_add_page_" + table_name } ) %>
    <%= hidden_field_tag(:table_name, table_name, { :id => "mass_add_tag_table_name_" + table_name } ) %>
    <%= submit_tag "Add tag to all", :class => "btn btn-primary" %>
    (in table just above)
  </p>
<% end %>

app/views/admin_public_body/_tag_help.html.erb
<h2>List of tags</h2>
<% first_row = true %>
<% for row in PublicBodyCategory.get().with_headings() %>
  <% if row.instance_of?(Array) %>
    <% if row[0] != 'other' %>
      <strong><%= row[0] %></strong>=<%= row[1] %>
      <br/>
    <% end %>
  <% elsif row != 'Miscellaneous' %>
    <% if not first_row %>
    <% else %>
      <% first_row = false %>
    <% end %>
    <h3><%=h row%></h3>
  <% end %>
<% end %>

app/views/admin_public_body/_tags.html.erb
<% for t in body.tags %>
  <span class="label label-info tag">
    <% if t.value %>
      <%= link_to(h(t.name), list_public_bodies_path(:tag => t.name)) %>:<%= link_to(h(t.value), list_public_bodies_path(:tag => t.name_and_value)) %>
    <% else %>
      <%= link_to(h(t.name), list_public_bodies_path(:tag => t.name)) %>
    <% end %>
  </span>
<% end %>

app/views/admin_public_body/edit.html.erb
<h1><%=@title%></h1>

<div class="row">
  <div class="span8">
    <div id="public_body_form">
      <%= form_for @public_body, :url => admin_body_path(@public_body),  :method => 'put', :html => { :class => "form form-horizontal" } do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
        <div class="form-actions">
          <%= f.submit 'Save', :accesskey => 's', :class => "btn btn-success" %></p>
        </div>
      <% end %>

      <div class="row">
        <div class="span8">
          <div class="well">
            <%= link_to 'Show', admin_body_path(@public_body), :class => "btn" %>
            <%= link_to 'List all', admin_bodies_path, :class => "btn" %>
          </div>
        </div>
      </div>

      <%= form_tag admin_body_path(@public_body),
                   class: 'form form-inline',
                   method: 'delete' do %>
        <% button_opts = { class: 'btn btn-danger' } %>
          <% if @hide_destroy_button
             button_opts[:disabled] = true
             button_opts[:title] =
               "This authority has #{@public_body.info_requests.count} " \
               "requests (may be embargoed)"
          end %>
        <%= submit_tag "Destroy #{@public_body.name}", button_opts %>
        (this is permanent!)
      <% end %>
    </div>

  </div>
  <div class="span4">
    <%= render :partial => 'tag_help' %>
  </div>
</div>

app/views/admin_public_body/index.html.erb
<% if @query.nil? %>
  <% @title = _('Listing public authorities') %>
<% else %>
  <% @title = _("Listing public authorities matching '{{query}}'", :query => @query ) %>
<% end %>

<h1><%=@title%></h1>

<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to 'New public authority', new_admin_body_path, :class => "btn btn-primary" %>
  </div>
  <div class="btn-group">
    <%= link_to 'Import from CSV file', import_csv_admin_bodies_path, :class => "btn btn-warning" %>
  </div>
</div>

<%= form_tag({}, :method => "get", :class => "form form-search") do %>
  <%= text_field_tag 'query', params[:query], { :size => 30, :class => "input-large search-query" } %>
  <%= submit_tag "Search", :class => "btn" %>
  <% if !@query.nil? %>
    <%= link_to 'Show all', admin_bodies_path, :class => "btn" %>
  <% end %><br>
  (substring search in names and emails; exact match of tags)
<% end %>


<% if @public_bodies_by_tag.size > 0 %>
  <h2>Exact tag matches (<%= @public_bodies_by_tag.size %> total)</h2>
  <%= render :partial => 'one_list', :locals => { :bodies => @public_bodies_by_tag, :table_name => 'exact' } %>
<% end %>

<% if @public_bodies.size > 0 %>
  <% if @query.nil? %>
    <h2>All authorities</h2>
  <% else %>
    <h2>Substring search matches (<%= @public_bodies.total_entries %> total)</h2>
  <% end %>
  <%= render :partial => 'one_list', :locals => { :bodies => @public_bodies, :table_name => 'substring' } %>
<% end %>

<%= will_paginate(@public_bodies, :class => "paginator") %>

app/views/admin_public_body/missing_scheme.html.erb
<% @title = 'Popular authorities without Publication Scheme' %>

<h1><%=@title%></h1>
<p><%= @stats["entered"] %> of <%= @stats["total"] %> entered</p>

<ol>
  <% for public_body in @public_bodies %>
    <li><%= public_body_both_links(public_body) %></li>
  <% end %>
</ol>

app/views/admin_public_body/new.html.erb
<% @title = 'New public authority' %>

<h1><%=@title%></h1>
<div class="row">
  <div class="span8">
    <div id="public_body_form">
      <%= form_for @public_body, :as => :public_body, :url => admin_bodies_path, :html => {:class => "form form-horizontal"} do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>


        <div class="form-actions">
          <%= f.submit "Create", :class => "btn btn-primary"  %>
        </div>
      <% end %>
      <div class="row">
        <div class="span8 well">
          <%= link_to 'List all', admin_bodies_path, :class => "btn" %>
        </div>
      </div>
    </div>
  </div>
  <div class="span4">
    <% if @public_body.ordered_translations.many? %>
      <div class="alert alert-info">
        <i class="icon-info-sign"></i>
        Make sure you add the request email for <em>all</em> locales.
      </div>
    <% end %>

    <%= render :partial => 'tag_help' %>
  </div>
</div>

app/views/admin_public_body/show.html.erb
<% @title = _("Public authority – {{name}}", :name => h(@public_body.name)) %>

<h1><%=@title%></h1>

<table class="table table-striped table-condensed">
  <tbody>
    <% @public_body.for_admin_column do |name, value, type, column_name| %>
      <% unless (column_name == 'api_key' && cannot?(:read, :api_key)) %>
        <tr>
          <td>
            <b><%=name%></b>
          </td>
          <td>
            <% if ['home_page', 'publication_scheme', 'disclosure_log'].include? column_name %>
              <% if value %>
                <%= link_to h(value), value  %>
              <% end %>
            <% elsif column_name == 'request_email' %>
              <%= link_to(h(value), "mailto:#{value}")  %>
              <% unless @public_body.is_requestable? %>
                <%=_("not requestable due to: {{reason}}", :reason => h(@public_body.not_requestable_reason))%><% if @public_body.is_followupable? %>; <%=_("but followupable")%><% end %>
              <% end %>
            <% else %>
              <%=h value %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <td>
        <b><%=_("Calculated home page")%></b>
      </td>
      <td>
        <% unless @public_body.calculated_home_page.nil? %>
          <%= link_to(h(@public_body.calculated_home_page), @public_body.calculated_home_page) %>
        <% else %>
          <%=_("*unknown*")%>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%=_("Tags")%></b>
      </td>
      <td>
        <%= render :partial => 'tags', :locals => { :body => @public_body} %>
      </td>
    </tr>
  </tbody>
</table>
<%= link_to _("Edit"), edit_admin_body_path(@public_body), :class => "btn btn-primary" %>
<% unless @public_body.url_name.nil? %>
  <%=link_to _("Public page"), public_body_path(@public_body), :class => "btn" %>
<% else %>
  <%=_("Public page not available")%>
<% end %>
<hr>
<h2>History</h2>
  <% @versions.each_with_index do |version, i| %>
  <div class="row">
    <div class="span2">
      <b>
        <%= _("Version {{version}}", :version => version.version)%>
      </b>
    </div>
    <div class="span4">
      <%= I18n.l(version.updated_at, :format => "%e %B %Y %H:%M:%S") %>
      (<%= _('{{length_of_time}} ago', :length_of_time => time_ago_in_words(version.updated_at)) %>)
    </div>
    <% if i == @versions.length - 1 %>
      <div class="span6">
        <p>“<%= h(version.last_edit_comment) %>”</p>
        <ul>
          <li><%=_("This is the first version.")%></li>
        </ul>
      </div>
    <% else %>
      <div class="span6">
        <p>“<%= h(version.last_edit_comment) %>”</p>
        <ul>
          <% version.compare(@versions[i+1]) do |change| %>
            <li>
              <%= _("{{thing_changed}} was changed from <code>{{from_value}}</code> to <code>{{to_value}}</code>",
                :thing_changed => change[:name],
                :from_value => (change[:from] or "-"),
                :to_value => (change[:to] or "-")) %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>
<hr>
<h2>Requests</h2>
<%= render :partial => 'admin_request/some_requests', :locals => { :info_requests => @info_requests } %>

<hr>

<h2>Track things</h2>
<%= render :partial => 'admin_track/some_tracks', :locals => { :track_things => @public_body.track_things, :include_destroy => true } %>

<hr>

<h2>Censor rules</h2>
<%= render :partial => 'admin_censor_rule/show', :locals => { :censor_rules => @public_body.censor_rules, :public_body => @public_body } %>